[work]
name = 'FT-2-model-fluct' # name of calculation
description = 'model fluct FT-2 '

[series]
number = 4
var = 'Nr'
var_type = 'int'
start = 1501
step = 50

[params]
field_solver_ver = 2 # 0 old, 1 MKL+OMP, 2 (MKL+OMP+no_inv_mat)

[w2grid]
# comments
Nr = 1601	  # number of radial points
nphi1 = 0	  # integer start toroidal wavenumber (Ntor1 = nphi1/R)
nphi2 = 0	  # integer final toroidal wavenumber (Ntor2 = nphi2/R)
nphistep = 1      # integer step for toroidal mode number
Mmax = 168        # maximum poloidal mode number
Mspow_excess = 0  # Mspow_excess (non-negative): Msmax = Msmax_min_permissible * 2**Mspow_excess
Pinterv = 0       # number of traced time intervals

[w2source]
# comments
AntType = 3	  # 0-Sngl.Mode, 1-Grill, 2-Strap, 3-Spher.Front, 4-Gaus.Beam, 5-File, 6-BasicSet, 7-Imped
Pinp = 1.0	  # Pinp(kW)

